name: CI/CD

on:
  push:
    branches:
      - 'master'

jobs:

 chekout:
    runs-on: alpine-latest
    
    steps:
    - uses: actions/chekout@v2

 ng-test:
    runs-on: alpine-latest
    
    steps:
    - name: test
      run: ng test --single-run
        

