name: My-Test-Task

on: push

jobs:

  tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./angular

    steps:
      - uses: actions/checkout@v3
      # make file with current time inside so we can meassure pipeline exectuion total time
#      - name: Start time meassure
#        run: echo "$(date +%s)" > ./test.txt

#      - uses: actions/upload-artifact@v3
#        with:
#          name: my-artifact
#          path: ./angular/test.txt
          
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          
      - name: Setup ci
        run: npm ci
#      - name: Setup
#        run: npm run lint

      - name: run tests
        run: npm run test -- --no-watch --no-progress --browsers=ChromeHeadless
        
      - name: Build
        run: npm run build
      - name: List direction
        run : ls -la
        

        

